#!/bin/bash

# Smart Nose TPA - Quick Deployment Script
# Run this script untuk quick deployment guide

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       🌬️  Smart Nose TPA - Deployment Quick Start         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Project Setup Selesai! Berikut file yang sudah disiapkan:"
echo ""
echo "📁 Root Files:"
echo "   • index.html ........................ Aplikasi utama"
echo "   • manifest.json ..................... PWA manifest"
echo "   • package.json ...................... Npm configuration"
echo "   • vercel.json ....................... Vercel deployment config"
echo "   • .env.example ....................... Template environment variables"
echo "   • .env.local ......................... Environment variables (local)"
echo "   • .gitignore ......................... Git ignore rules"
echo ""

echo "📁 API Folder:"
echo "   • api/readings.js ................... Vercel serverless endpoint"
echo ""

echo "📁 Documentation:"
echo "   • DEPLOYMENT_GUIDE.md .............. Panduan lengkap deployment"
echo "   • DEPLOYMENT_CHECKLIST.md ......... Checklist step-by-step"
echo "   • ESP32_Sketch.ino ................. Arduino sketch untuk sensor"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "🚀 QUICK START (3 Steps):"
echo ""
echo "STEP 1 - Siapkan Supabase"
echo "  → Buka: https://app.supabase.com"
echo "  → Create new project"
echo "  → Copy Project URL dan Anon Key"
echo "  → Edit file: .env.local dengan credentials"
echo ""

echo "STEP 2 - Push ke GitHub"
echo "  → Buat GitHub repository baru: 'smartnose2'"
echo "  → Jalankan di folder ini:"
echo "     git init"
echo "     git add ."
echo "     git commit -m 'Initial: Smart Nose TPA'"
echo "     git branch -M main"
echo "     git remote add origin https://github.com/USERNAME/smartnose2"
echo "     git push -u origin main"
echo ""

echo "STEP 3 - Deploy ke Vercel"
echo "  → Buka: https://vercel.com"
echo "  → Click 'Add New' → 'Project'"
echo "  → Select GitHub repository 'smartnose2'"
echo "  → Add Environment Variables:"
echo "     SUPABASE_URL = [Supabase URL Anda]"
echo "     SUPABASE_ANON_KEY = [Anon Key Anda]"
echo "  → Click 'Deploy'"
echo "  → Tunggu ±2-3 menit, dapatkan URL"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "📖 Documentation:"
echo ""
echo "  • Untuk panduan LENGKAP:"
echo "    → Baca: DEPLOYMENT_GUIDE.md"
echo ""
echo "  • Untuk step-by-step checklist:"
echo "    → Baca: DEPLOYMENT_CHECKLIST.md"
echo ""
echo "  • Untuk setup ESP32 sensor:"
echo "    → Edit file: ESP32_Sketch.ino dengan credentials WiFi"
echo "    → Upload ke ESP32 menggunakan Arduino IDE"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "🔑 Environment Variables (.env.local):"
echo ""
echo "SUPABASE_URL=https://your-project.supabase.co"
echo "SUPABASE_ANON_KEY=your-anon-key-here"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "✨ File Structure:"
echo ""
echo "smartnose2/"
echo "├── .env.example              (Template untuk env variables)"
echo "├── .env.local                (Local development config - jangan commit)"
echo "├── .gitignore                (Git ignore rules)"
echo "├── package.json              (Npm dependencies)"
echo "├── vercel.json               (Vercel configuration)"
echo "├── index.html                (Aplikasi utama)"
echo "├── manifest.json             (PWA manifest)"
echo "├── DEPLOYMENT_GUIDE.md       (Panduan lengkap)"
echo "├── DEPLOYMENT_CHECKLIST.md   (Checklist)"
echo "├── ESP32_Sketch.ino          (Arduino code untuk sensor)"
echo "└── api/"
echo "    └── readings.js           (Vercel API endpoint)"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "⚠️  PENTING:"
echo "  1. Jangan commit .env.local ke GitHub (already in .gitignore)"
echo "  2. Update .env.local dengan Supabase credentials Anda"
echo "  3. Baca DEPLOYMENT_GUIDE.md untuk panduan lengkap"
echo "  4. Setup RLS (Row Level Security) di Supabase untuk security"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "🔗 Links:"
echo "  • Vercel: https://vercel.com"
echo "  • Supabase: https://supabase.com"
echo "  • GitHub: https://github.com"
echo ""

echo "✅ Semua file siap untuk deployment!"
echo ""
